-- Generated from free-exercise-db (873 exercises)
-- Images: musclewiki.com CDN (animated exercise demos)
SET @coach_id = 1;

INSERT INTO course (coach_id, title, description, category, difficulty, duration, price, status, rating, rating_count) VALUES
(@coach_id, '胸部训练完全指南', '系统化训练胸大肌各个角度，打造饱满有型胸肌线条。', 'STRENGTH', 'INTERMEDIATE', 63, 99, 'APPROVED', 4.6, 672);
SET @c = LAST_INSERT_ID();
INSERT INTO course_exercise (course_id, title, video_url, description, sort_order) VALUES
(@c, 'Alternating Floor Press', '/exercises/Alternating_Floor_Press/', 'Lie on the floor with two kettlebells next to your shoulders. Position one in place on your chest and then the other, gripping the kettlebells on the handle with the palms facing forward. Extend both arms, so that the kettlebells are being held above your chest. Lower one kettlebell, bringing it to your chest and turn the wrist in the direction of the locked out kettlebell. Raise the kettlebell and repeat on the opposite side.', 1),
(@c, 'Barbell Bench Press - Medium Grip', '/exercises/Barbell_Bench_Press_-_Medium_Grip/', 'Lie back on a flat bench. Using a medium width grip (a grip that creates a 90-degree angle in the middle of the movement between the forearms and the upper arms), lift the bar from the rack and hold it straight over you with your arms locked. This will be your starting position. From the starting position, breathe in and begin coming down slowly until the bar touches your middle chest. After a brief pause, push the bar back to the starting position as you breathe out. Focus on pushing the bar using your chest muscles. Lock your arms and squeeze your chest in the contracted position at the top ', 2),
(@c, 'Barbell Incline Bench Press - Medium Grip', '/exercises/Barbell_Incline_Bench_Press_-_Medium_Grip/', 'Lie back on an incline bench. Using a medium-width grip (a grip that creates a 90-degree angle in the middle of the movement between the forearms and the upper arms), lift the bar from the rack and hold it straight over you with your arms locked. This will be your starting position. As you breathe in, come down slowly until you feel the bar on you upper chest. After a second pause, bring the bar back to the starting position as you breathe out and push the bar using your chest muscles. Lock your arms in the contracted position, squeeze your chest, hold for a second and then start coming down s', 3),
(@c, 'Around The Worlds', '/exercises/Around_The_Worlds/', 'Lay down on a flat bench holding a dumbbell in each hand with the palms of the hands facing towards the ceiling. Tip: Your arms should be parallel to the floor and next to your thighs. To avoid injury, make sure that you keep your elbows slightly bent. This will be your starting position. Now move the dumbbells by creating a semi-circle as you displace them from the initial position to over the head. All of the movement should happen with the arms parallel to the floor at all times. Breathe in as you perform this portion of the movement. Reverse the movement to return the weight to the startin', 4),
(@c, 'Barbell Guillotine Bench Press', '/exercises/Barbell_Guillotine_Bench_Press/', 'Using a medium width grip (a grip that creates a 90-degree angle in the middle of the movement between the forearms and the upper arms), lift the bar from the rack and hold it straight over your neck with your arms locked. This will be your starting position. As you breathe in, bring the bar down slowly until it is about 1 inch from your neck. After a second pause, bring the bar back to the starting position as you breathe out and push the bar using your chest muscles. Lock your arms and squeeze your chest in the contracted position, hold for a second and then start coming down slowly again. I', 5),
(@c, 'Behind Head Chest Stretch', '/exercises/Behind_Head_Chest_Stretch/', 'Sit upright on the floor with your partner behind you. Place your hands behind your hand, and push your elbows back as far as you can. Your partner should hold your elbows. This will be your starting position. Gently attempt to pull your elbows forward with your hands still behind your head for 10 or more seconds. Your partner should prevent your elbows from moving. Now, relax your muscles and have your partner gently pull the elbows back as far as it comfortable for you. Be sure to let your partner know when the stretch is adequate to prevent overstretching or injury.', 6);

INSERT INTO course (coach_id, title, description, category, difficulty, duration, price, status, rating, rating_count) VALUES
(@coach_id, '肩部宽度与力量训练', '涵盖前束、中束、后束的全面训练，塑造宽阔有力肩膀。', 'STRENGTH', 'INTERMEDIATE', 63, 99, 'APPROVED', 4.7, 999);
SET @c = LAST_INSERT_ID();
INSERT INTO course_exercise (course_id, title, video_url, description, sort_order) VALUES
(@c, 'Alternating Cable Shoulder Press', '/exercises/Alternating_Cable_Shoulder_Press/', 'Move the cables to the bottom of the tower and select an appropriate weight. Grasp the cables and hold them at shoulder height, palms facing forward. This will be your starting position. Keeping your head and chest up, extend through the elbow to press one side directly over head. After pausing at the top, return to the starting position and repeat on the opposite side.', 1),
(@c, 'Alternating Deltoid Raise', '/exercises/Alternating_Deltoid_Raise/', 'In a standing position, hold a pair of dumbbells at your side. Keeping your elbows slightly bent, raise the weights directly in front of you to shoulder height, avoiding any swinging or cheating. Return the weights to your side. On the next repetition, raise the weights laterally, raising them out to your side to about shoulder height.', 2),
(@c, 'Anti-Gravity Press', '/exercises/Anti-Gravity_Press/', 'Place a bar on the ground behind the head of an incline bench. Lay on the bench face down. With a pronated grip, pick the barbell up from the floor. Flex the elbows, performing a reverse curl to bring the bar near your chest. This will be your starting position. To begin, press the barbell out in front of your head by extending your elbows. Keep your arms parallel to the ground throughout the movement. Return to the starting position and repeat to complete the set.', 3),
(@c, 'Alternating Kettlebell Press', '/exercises/Alternating_Kettlebell_Press/', 'Clean two kettlebells to your shoulders. Clean the kettlebells to your shoulders by extending through the legs and hips as you pull the kettlebells towards your shoulders. Rotate your wrists as you do so. Press one directly overhead by extending through the elbow, turning it so the palm faces forward while holding the other kettlebell stationary . Lower the pressed kettlebell to the starting position and immediately press with your other arm.', 4),
(@c, 'Arnold Dumbbell Press', '/exercises/Arnold_Dumbbell_Press/', 'Sit on an exercise bench with back support and hold two dumbbells in front of you at about upper chest level with your palms facing your body and your elbows bent. Tip: Your arms should be next to your torso. The starting position should look like the contracted portion of a dumbbell curl. Now to perform the movement, raise the dumbbells as you rotate the palms of your hands until they are facing forward. Continue lifting the dumbbells until your arms are extended above you in straight arm position. Breathe out as you perform this portion of the movement. After a second pause at the top, begin', 5),
(@c, 'Circus Bell', '/exercises/Circus_Bell/', 'The circus bell is an oversized dumbbell with a thick handle. Begin with the dumbbell between your feet, and grip the handle with both hands. Clean the dumbbell by extending through your hips and knees to deliver the implement to the desired shoulder, letting go with the extra hand. Ensure that you get one of the dumbbell heads behind the shoulder to keep from being thrown off balance. To raise it overhead, dip by flexing the knees, and the drive upwards as you extend the dumbbell overhead, leaning slightly away from it as you do so. Carefully guide the bell back to the floor, keeping it under', 6);

INSERT INTO course (coach_id, title, description, category, difficulty, duration, price, status, rating, rating_count) VALUES
(@coach_id, '背阔肌宽度训练', '引体向上、划船、下拉——打造V型背部轮廓黄金组合。', 'STRENGTH', 'INTERMEDIATE', 63, 100, 'APPROVED', 4.4, 304);
SET @c = LAST_INSERT_ID();
INSERT INTO course_exercise (course_id, title, video_url, description, sort_order) VALUES
(@c, 'Band Assisted Pull-Up', '/exercises/Band_Assisted_Pull-Up/', 'Choke the band around the center of the pullup bar. You can use different bands to provide varying levels of assistance. Pull the end of the band down, and place one bent knee into the loop, ensuring it won''t slip out. Take a medium to wide grip on the bar. This will be your starting position. Pull yourself upward by contracting the lats as you flex the elbow. The elbow should be driven to your side. Pull to the front, attempting to get your chin over the bar. Avoid swinging or jerking movements. After a brief pause, return to the starting position.', 1),
(@c, 'Cable Incline Pushdown', '/exercises/Cable_Incline_Pushdown/', 'Lie on incline an bench facing away from a high pulley machine that has a straight bar attachment on it. Grasp the straight bar attachment overhead with a pronated (overhand; palms down) shoulder width grip and extend your arms in front of you. The bar should be around 2 inches away from your upper thighs. This will be your starting position. Keeping the upper arms stationary, lift your arms back in a semi circle until the bar is straight over your head. Breathe in during this portion of the movement. Slowly go back to the starting position using your lats and hold the contraction once you rea', 2),
(@c, 'Catch and Overhead Throw', '/exercises/Catch_and_Overhead_Throw/', 'Begin standing while facing a wall or a partner. Using both hands, position the ball behind your head, stretching as much as possible, and forcefully throw the ball forward. Ensure that you follow your throw through, being prepared to receive your rebound from your throw. If you are throwing against the wall, make sure that you stand close enough to the wall to receive the rebound, and aim a little higher than you would with a partner.', 3),
(@c, 'Bent-Arm Barbell Pullover', '/exercises/Bent-Arm_Barbell_Pullover/', 'Lie on a flat bench with a barbell using a shoulder grip width. Hold the bar straight over your chest with a bend in your arms. This will be your starting position. While keeping your arms in the bent arm position, lower the weight slowly in an arc behind your head while breathing in until you feel a stretch on the chest. At that point, bring the barbell back to the starting position using the arc through which the weight was lowered and exhale as you perform this movement.', 4),
(@c, 'Elevated Cable Rows', '/exercises/Elevated_Cable_Rows/', 'Get a platform of some sort (it can be an aerobics or calf raise platform) that is around 4-6 inches in height. Place it on the seat of the cable row machine. Sit down on the machine and place your feet on the front platform or crossbar provided making sure that your knees are slightly bent and not locked. Lean over as you keep the natural alignment of your back and grab the V-bar handles.', 5),
(@c, 'Overhead Lat', '/exercises/Overhead_Lat/', 'Sit upright on the floor with your partner behind you. Raise one arm straight up, and flex the elbow, attempting to touch your hand to your back. Your parner should hold your tricep and wrist. This will be your starting position. Attempt to pull your upper arm to your side as your partner prevents you from doing actually doing so. After 10-20 seconds, relax the arm and allow your partner to further stretch the lat by applying gentle pressure to the tricep. Hold for 10-20 seconds, and then switch sides.', 6);

INSERT INTO course (coach_id, title, description, category, difficulty, duration, price, status, rating, rating_count) VALUES
(@coach_id, '腿部力量基础训练', '深蹲、腿举、弓步——下肢力量三大根基，一切运动表现的基础。', 'STRENGTH', 'INTERMEDIATE', 63, 100, 'APPROVED', 4.8, 999);
SET @c = LAST_INSERT_ID();
INSERT INTO course_exercise (course_id, title, video_url, description, sort_order) VALUES
(@c, 'Alternate Leg Diagonal Bound', '/exercises/Alternate_Leg_Diagonal_Bound/', 'Assume a comfortable stance with one foot slightly in front of the other. Begin by pushing off with the front leg, driving the opposite knee forward and as high as possible before landing. Attempt to cover as much distance to each side with each bound. It may help to use a line on the ground to guage distance from side to side. Repeat the sequence with the other leg.', 1),
(@c, 'Backward Drag', '/exercises/Backward_Drag/', 'Load a sled with the desired weight, attaching a rope or straps to the sled that you can hold onto. Begin the exercise by moving backwards for a given distance. Leaning back, extend through the legs for short steps to move as quickly as possible.', 2),
(@c, 'Barbell Side Split Squat', '/exercises/Barbell_Side_Split_Squat/', 'Stand up straight while holding a barbell placed on the back of your shoulders (slightly below the neck). Your feet should be placed wide apart with the foot of the lead leg angled out to the side. This will be your starting position. Lower your body towards the side of your angled foot by bending the knee and hip of your lead leg and while keeping the opposite leg only slightly bent. Breathe in as you lower your body. Return to the starting position by extending the hip and knee of the lead leg. Breathe out as you perform this movement. After performing the recommended amount of reps, repeat ', 3),
(@c, 'All Fours Quad Stretch', '/exercises/All_Fours_Quad_Stretch/', 'Start off on your hands and knees, then lift your leg off the floor and hold the foot with your hand. Use your hand to hold the foot or ankle, keeping the knee fully flexed, stretching the quadriceps and hip flexors. Focus on extending your hips, thrusting them towards the floor. Hold for 10-20 seconds and then switch sides.', 4),
(@c, 'Barbell Full Squat', '/exercises/Barbell_Full_Squat/', 'This exercise is best performed inside a squat rack for safety purposes. To begin, first set the bar on a rack just above shoulder level. Once the correct height is chosen and the bar is loaded, step under the bar and place the back of your shoulders (slightly below the neck) across it. Hold on to the bar using both arms at each side and lift it off the rack by first pushing with your legs and at the same time straightening your torso. Step away from the rack and position your legs using a shoulder-width medium stance with the toes slightly pointed out. Keep your head up at all times and maint', 5),
(@c, 'Barbell Squat To A Bench', '/exercises/Barbell_Squat_To_A_Bench/', 'This exercise is best performed inside a squat rack for safety purposes. To begin, first place a flat bench or a box behind you. The flat bench is used to teach you to set your hips back and to hit depth.  Then, set the bar on a rack that best matches your height. Once the correct height is chosen and the bar is loaded, step under the bar and place the back of your shoulders (slightly below the neck) across it. Hold on to the bar using both arms at each side and lift it off the rack by first pushing with your legs and at the same time straightening your torso.', 6);

INSERT INTO course (coach_id, title, description, category, difficulty, duration, price, status, rating, rating_count) VALUES
(@coach_id, '腘绳肌与后链训练', '强化大腿后侧肌群，提升短跑速度、弹跳力和硬拉成绩。', 'STRENGTH', 'INTERMEDIATE', 63, 101, 'APPROVED', 4.6, 632);
SET @c = LAST_INSERT_ID();
INSERT INTO course_exercise (course_id, title, video_url, description, sort_order) VALUES
(@c, '90/90 Hamstring', '/exercises/90_90_Hamstring/', 'Lie on your back, with one leg extended straight out. With the other leg, bend the hip and knee to 90 degrees. You may brace your leg with your hands if necessary. This will be your starting position. Extend your leg straight into the air, pausing briefly at the top. Return the leg to the starting position. Repeat for 10-20 repetitions, and then switch to the other leg.', 1),
(@c, 'Ball Leg Curl', '/exercises/Ball_Leg_Curl/', 'Begin on the floor laying on your back with your feet on top of the ball. Position the ball so that when your legs are extended your ankles are on top of the ball. This will be your starting position. Raise your hips off of the ground, keeping your weight on the shoulder blades and your feet. Flex the knees, pulling the ball as close to you as you can, contracting the hamstrings.', 2),
(@c, 'Band Good Morning', '/exercises/Band_Good_Morning/', 'Using a 41 inch band, stand on one end, spreading your feet a small amount. Bend at the hips to loop the end of the band behind your neck. This will be your starting position. Keeping your legs straight, extend through the hips to come to a near vertical position. Ensure that you do not round your back as you go down back to the starting position.', 3),
(@c, 'Alternating Hang Clean', '/exercises/Alternating_Hang_Clean/', 'Place two kettlebells between your feet. To get in the starting position, push your butt back and look straight ahead. Clean one kettlebell to your shoulder and hold on to the other kettlebell in a hanging position. Clean the kettlebell to your shoulder by extending through the legs and hips as you pull the kettlebell towards your shoulders. Rotate your wrist as you do so. Lower the cleaned kettlebell to a hanging position and clean the alternate kettlebell. Repeat.', 4),
(@c, 'Clean', '/exercises/Clean/', 'With a barbell on the floor close to the shins, take an overhand (or hook) grip just outside the legs. Lower your hips with the weight focused on the heels, back straight, head facing forward, chest up, with your shoulders just in front of the bar. This will be your starting position.  Begin the first pull by driving through the heels, extending your knees. Your back angle should stay the same, and your arms should remain straight. Move the weight with control as you continue to above the knees. Next comes the second pull, the main source of acceleration for the clean. As the bar approaches th', 5),
(@c, 'Hang Snatch', '/exercises/Hang_Snatch/', 'Begin with a wide grip on the bar, with an overhand or hook grip. The feet should be directly below the hips with the feet turned out. Your knees should be slightly bent, and the torso inclined forward. The spine should be fully extended and the head facing forward. The bar should be at the hips. This will be your starting position. Aggressively extend through the legs and hips. At peak extension, shrug the shoulders and allow the elbows to flex to the side. As you move your feet into the receiving position, forcefully pull yourself below the bar as you elevate the bar overhead. Receive the ba', 6);

INSERT INTO course (coach_id, title, description, category, difficulty, duration, price, status, rating, rating_count) VALUES
(@coach_id, '臀肌激活与塑形', '激活沉睡臀肌，改善体态，提升髋关节稳定性。', 'STRENGTH', 'INTERMEDIATE', 63, 102, 'APPROVED', 4.4, 176);
SET @c = LAST_INSERT_ID();
INSERT INTO course_exercise (course_id, title, video_url, description, sort_order) VALUES
(@c, 'Ankle On The Knee', '/exercises/Ankle_On_The_Knee/', 'From a lying position, bend your knees and keep your feet on the floor. Place your ankle of one foot on your opposite knee. Grasp the thigh or knee of the bottom leg and pull both of your legs into the chest. Relax your neck and shoulders. Hold for 10-20 seconds and then switch sides.', 1),
(@c, 'Butt Lift (Bridge)', '/exercises/Butt_Lift_Bridge/', 'Lie flat on the floor on your back with the hands by your side and your knees bent. Your feet should be placed around shoulder width. This will be your starting position. Pushing mainly with your heels, lift your hips off the floor while keeping your back straight. Breathe out as you perform this part of the motion and hold at the top for a second. Slowly go back to the starting position as you breathe in.', 2),
(@c, 'Flutter Kicks', '/exercises/Flutter_Kicks/', 'On a flat bench lie facedown with the hips on the edge of the bench, the legs straight with toes high off the floor and with the arms on top of the bench holding on to the front edge. Squeeze your glutes and hamstrings and straighten the legs until they are level with the hips. This will be your starting position. Start the movement by lifting the left leg higher than the right leg. Then lower the left leg as you lift the right leg.', 3),
(@c, 'Barbell Glute Bridge', '/exercises/Barbell_Glute_Bridge/', 'Begin seated on the ground with a loaded barbell over your legs. Using a fat bar or having a pad on the bar can greatly reduce the discomfort caused by this exercise. Roll the bar so that it is directly above your hips, and lay down flat on the floor. Begin the movement by driving through with your heels, extending your hips vertically through the bar. Your weight should be supported by your upper back and the heels of your feet. Extend as far as possible, then reverse the motion to return to the starting position.', 4),
(@c, 'Barbell Hip Thrust', '/exercises/Barbell_Hip_Thrust/', 'Begin seated on the ground with a bench directly behind you. Have a loaded barbell over your legs. Using a fat bar or having a pad on the bar can greatly reduce the discomfort caused by this exercise. Roll the bar so that it is directly above your hips, and lean back against the bench so that your shoulder blades are near the top of it. Begin the movement by driving through your feet, extending your hips vertically through the bar. Your weight should be supported by your shoulder blades and your feet. Extend as far as possible, then reverse the motion to return to the starting position.', 5),
(@c, 'Kneeling Jump Squat', '/exercises/Kneeling_Jump_Squat/', 'Begin kneeling on the floor with a barbell racked across the back of your shoulders, or you can use your body weight for this exercise. This can be done inside of a power rack to make unracking easier. Sit back with your hips until your glutes touch your feet, keeping your head and chest up. Explode up with your hips, generating enough power to land with your feet flat on the floor. Continue with the squat by driving through your heels and extending the knees to come to a standing position.', 6);

INSERT INTO course (coach_id, title, description, category, difficulty, duration, price, status, rating, rating_count) VALUES
(@coach_id, '肱二头肌雕刻训练', '弯举的百种变化——全方位刺激肱二头肌长头和短头。', 'STRENGTH', 'INTERMEDIATE', 63, 102, 'APPROVED', 4.5, 424);
SET @c = LAST_INSERT_ID();
INSERT INTO course_exercise (course_id, title, video_url, description, sort_order) VALUES
(@c, 'Alternate Hammer Curl', '/exercises/Alternate_Hammer_Curl/', 'Stand up with your torso upright and a dumbbell in each hand being held at arms length. The elbows should be close to the torso. The palms of the hands should be facing your torso. This will be your starting position. While holding the upper arm stationary, curl the right weight forward while contracting the biceps as you breathe out. Continue the movement until your biceps is fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a second as you squeeze the biceps. Tip: Only the forearms should move. Slowly begin to bring the dumbbells back to starting posi', 1),
(@c, 'Alternate Incline Dumbbell Curl', '/exercises/Alternate_Incline_Dumbbell_Curl/', 'Sit down on an incline bench with a dumbbell in each hand being held at arms length. Tip: Keep the elbows close to the torso.This will be your starting position. While holding the upper arm stationary, curl the right weight forward while contracting the biceps as you breathe out. As you do so, rotate the hand so that the palm is facing up. Continue the movement until your biceps is fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a second as you squeeze the biceps. Tip: Only the forearms should move. Slowly begin to bring the dumbbell back to starting ', 2),
(@c, 'Barbell Curl', '/exercises/Barbell_Curl/', 'Stand up with your torso upright while holding a barbell at a shoulder-width grip. The palm of your hands should be facing forward and the elbows should be close to the torso. This will be your starting position. While holding the upper arms stationary, curl the weights forward while contracting the biceps as you breathe out. Tip: Only the forearms should move. Continue the movement until your biceps are fully contracted and the bar is at shoulder level. Hold the contracted position for a second and squeeze the biceps hard. Slowly begin to bring the bar back to starting position as your breath', 3),
(@c, 'Brachialis-SMR', '/exercises/Brachialis-SMR/', 'Lie on your side, with your upper arm against the foam roller. The upper arm should be more or less aligned with your body, with the outside of the bicep pressed against the foam roller. Raise your hips off of the floor, supporting your weight on your arm and on your feet. Hold for 10-30 seconds, and then switch sides.', 4),
(@c, 'Drag Curl', '/exercises/Drag_Curl/', 'Grab a barbell with a supinated grip (palms facing forward) and get your elbows close to your torso and back. This will be your starting position. As you exhale, curl the bar up while keeping the elbows to the back as you "Drag" the bar up by keeping it in contact with your torso. Tip: As you can see, you will not be keeping the elbows pinned to your sides, but instead you will be bringing them back. Also, do not lift your shoulders. Slowly go back to the starting position as you keep the bar in contact with the torso at all times. Repeat for the recommended amount of repetitions.', 5),
(@c, 'Seated Biceps', '/exercises/Seated_Biceps/', 'Sit on the floor with your knees bent and your partner standing behind you. Extend your arms straight behind you with your palms facing each other. Your partner will hold your wrists for you. This will be the starting position. Attempt to flex your elbows, while your partner prevents any actual movement. After 10-20 seconds, relax your arms while your partner gently pulls your wrists up to stretch your biceps. Be sure to let your partner know when the stretch is appropriate to prevent injury or overstretching.', 6);

INSERT INTO course (coach_id, title, description, category, difficulty, duration, price, status, rating, rating_count) VALUES
(@coach_id, '肱三头肌增肌计划', '手臂围度三分之二来自肱三头肌，撑爆你的袖口。', 'STRENGTH', 'INTERMEDIATE', 63, 103, 'APPROVED', 4.5, 568);
SET @c = LAST_INSERT_ID();
INSERT INTO course_exercise (course_id, title, video_url, description, sort_order) VALUES
(@c, 'Band Skull Crusher', '/exercises/Band_Skull_Crusher/', 'Secure a band to the base of a rack or the bench. Lay on the bench so that the band is lined up with your head. Take hold of the band, raising your elbows so that the upper arm is perpendicular to the floor. With the elbow flexed, the band should be above your head. This will be your starting position. Extend through the elbow to straighten your arm, keeping your upper arm in place. Pause at the top of the motion, and return to the starting position.', 1),
(@c, 'Bench Dips', '/exercises/Bench_Dips/', 'For this exercise you will need to place a bench behind your back. With the bench perpendicular to your body, and while looking away from it, hold on to the bench on its edge with the hands fully extended, separated at shoulder width. The legs will be extended forward, bent at the waist and perpendicular to your torso. This will be your starting position. Slowly lower your body as you inhale by bending at the elbows until you lower yourself far enough to where there is an angle slightly smaller than 90 degrees between the upper arm and the forearm. Tip: Keep the elbows as close as possible thr', 2),
(@c, 'Body Tricep Press', '/exercises/Body_Tricep_Press/', 'Position a bar in a rack at chest height. Standing, take a shoulder width grip on the bar and step a yard or two back, feet together and arms extended so that you are leaning on the bar. This will be your starting position. Begin by flexing the elbow, lowering yourself towards the bar. Pause, and then reverse the motion by extending the elbows.', 3),
(@c, 'Bench Press - Powerlifting', '/exercises/Bench_Press_-_Powerlifting/', 'Begin by lying on the bench, getting your head beyond the bar if possible. Tuck your feet underneath you and arch your back. Using the bar to help support your weight, lift your shoulder off the bench and retract them, squeezing the shoulder blades together. Use your feet to drive your traps into the bench. Maintain this tight body position throughout the movement. However wide your grip, it should cover the ring on the bar. Pull the bar out of the rack without protracting your shoulders. Focus on squeezing the bar and trying to pull it apart. Lower the bar to your lower chest or upper stomach', 4),
(@c, 'Board Press', '/exercises/Board_Press/', 'Begin by lying on the bench, getting your head beyond the bar if possible. One to five boards, made out of 2x6''s, can be screwed together and held in place by a training partner, bands, or just tucked under your shirt. Tuck your feet underneath you and arch your back. Using the bar to help support your weight, lift your shoulder off the bench and retract them, squeezing the shoulder blades together. Use your feet to drive your traps into the bench. Maintain this tight body position throughout the movement. You can take a standard bench grip, or shoulder width to focus on the triceps. Pull the', 5),
(@c, 'Bench Press with Chains', '/exercises/Bench_Press_with_Chains/', 'Adjust the leader chain, shortening it to the desired length.Place the chains on the sleeves of the bar. Lying on the bench, get your head beyond the bar if possible. Tuck your feet underneath you and arch your back. Using the bar to help support your weight, lift your shoulder off the bench and retract them, squeezing the shoulder blades together. Use your feet to drive your traps into the bench. Maintain this tight body position throughout the movement. However wide your grip, it should cover the ring on the bar. Pull the bar out of the rack without protracting your shoulders. Focus on squee', 6);

INSERT INTO course (coach_id, title, description, category, difficulty, duration, price, status, rating, rating_count) VALUES
(@coach_id, '腹部核心强化训练', '不止六块腹肌——强大核心是一切运动的基础。', 'STRENGTH', 'INTERMEDIATE', 63, 103, 'APPROVED', 4.6, 744);
SET @c = LAST_INSERT_ID();
INSERT INTO course_exercise (course_id, title, video_url, description, sort_order) VALUES
(@c, '3/4 Sit-Up', '/exercises/3_4_Sit-Up/', 'Lie down on the floor and secure your feet. Your legs should be bent at the knees. Place your hands behind or to the side of your head. You will begin with your back on the ground. This will be your starting position. Flex your hips and spine to raise your torso toward your knees. At the top of the contraction your torso should be perpendicular to the ground. Reverse the motion, going only ¾ of the way down.', 1),
(@c, 'Air Bike', '/exercises/Air_Bike/', 'Lie flat on the floor with your lower back pressed to the ground. For this exercise, you will need to put your hands beside your head. Be careful however to not strain with the neck as you perform it. Now lift your shoulders into the crunch position. Bring knees up to where they are perpendicular to the floor, with your lower legs parallel to the floor. This will be your starting position. Now simultaneously, slowly go through a cycle pedal motion kicking forward with the right leg and bringing in the knee of the left leg. Bring your right elbow close to your left knee by crunching to the side', 2),
(@c, 'Alternate Heel Touchers', '/exercises/Alternate_Heel_Touchers/', 'Lie on the floor with the knees bent and the feet on the floor around 18-24 inches apart. Your arms should be extended by your side. This will be your starting position. Crunch over your torso forward and up about 3-4 inches to the right side and touch your right heel as you hold the contraction for a second. Exhale while performing this movement. Now go back slowly to the starting position as you inhale. Now crunch over your torso forward and up around 3-4 inches to the left side and touch your left heel as you hold the contraction for a second. Exhale while performing this movement and then ', 3),
(@c, 'Ab Crunch Machine', '/exercises/Ab_Crunch_Machine/', 'Select a light resistance and sit down on the ab machine placing your feet under the pads provided and grabbing the top handles. Your arms should be bent at a 90 degree angle as you rest the triceps on the pads provided. This will be your starting position. At the same time, begin to lift the legs up as you crunch your upper torso. Breathe out as you perform this movement. Tip: Be sure to use a slow and controlled motion. Concentrate on using your abs to move the weight while relaxing your legs and feet. After a second pause, slowly return to the starting position as you breathe in. Repeat the', 4),
(@c, 'Ab Roller', '/exercises/Ab_Roller/', 'Hold the Ab Roller with both hands and kneel on the floor. Now place the ab roller on the floor in front of you so that you are on all your hands and knees (as in a kneeling push up position). This will be your starting position. Slowly roll the ab roller straight forward, stretching your body into a straight position. Tip: Go down as far as you can without touching the floor with your body. Breathe in during this portion of the movement. After a pause at the stretched position, start pulling yourself back to the starting position as you breathe out. Tip: Go slowly and keep your abs tight at a', 5),
(@c, 'Barbell Ab Rollout - On Knees', '/exercises/Barbell_Ab_Rollout_-_On_Knees/', 'Hold an Olympic barbell loaded with 5-10lbs on each side and kneel on the floor. Now place the barbell on the floor in front of you so that you are on all your hands and knees (as in a kneeling push up position). This will be your starting position. Slowly roll the barbell straight forward, stretching your body into a straight position. Tip: Go down as far as you can without touching the floor with your body. Breathe in during this portion of the movement. After a second pause at the stretched position, start pulling yourself back to the starting position as you breathe out. Tip: Go slowly and', 6);

INSERT INTO course (coach_id, title, description, category, difficulty, duration, price, status, rating, rating_count) VALUES
(@coach_id, '小腿肌群强化训练', '小腿常被忽视却是全身最耐劳肌群，完善腿部整体线条。', 'STRENGTH', 'INTERMEDIATE', 60, 104, 'APPROVED', 4.4, 224);
SET @c = LAST_INSERT_ID();
INSERT INTO course_exercise (course_id, title, video_url, description, sort_order) VALUES
(@c, 'Ankle Circles', '/exercises/Ankle_Circles/', 'Use a sturdy object like a squat rack to hold yourself. Lift the right leg in the air (just around 2 inches from the floor) and perform a circular motion with the big toe. Pretend that you are drawing a big circle with it. Tip: One circle equals 1 repetition. Breathe normally as you perform the movement. When you are done with the right foot, then repeat with the left leg.', 1),
(@c, 'Balance Board', '/exercises/Balance_Board/', 'Place a balance board in front of you. Stand up on it and try to balance yourself. Hold the balance for as long as desired.', 2),
(@c, 'Barbell Seated Calf Raise', '/exercises/Barbell_Seated_Calf_Raise/', 'Place a block about 12 inches in front of a flat bench. Sit on the bench and place the ball of your feet on the block. Have someone place a barbell over your upper thighs about 3 inches above your knees and hold it there. This will be your starting position. Raise up on your toes as high as possible as you squeeze the calves and as you breathe out.', 3),
(@c, 'Anterior Tibialis-SMR', '/exercises/Anterior_Tibialis-SMR/', 'Begin seated on the ground with your legs bent and your feet on the floor. Using a Muscle Roller or a rolling pin, apply pressure to the muscles on the outside of your shins. Work from just below the knee to above the ankle, pausing at points of tension for 10-30 seconds. Repeat on the other leg.', 4),
(@c, 'Calf Raise On A Dumbbell', '/exercises/Calf_Raise_On_A_Dumbbell/', 'Hang on to a sturdy object for balance and stand on a dumbbell handle, preferably one with round plates so that it rolls as in this manner you have to work harder to stabilize yourself; thus increasing the effectiveness of the exercise. Now roll your foot slightly forward so that you can get a nice stretch of the calf. This will be your starting position. Lift the calf as you roll your foot over the top of the handle so that you get a full extension. Exhale during the execution of this movement. Contract the calf hard at the top and hold for a second. Tip: As you come up, roll the dumbbell sli', 5);

INSERT INTO course (coach_id, title, description, category, difficulty, duration, price, status, rating, rating_count) VALUES
(@coach_id, '前臂与握力训练', '强壮前臂和握力对大重量训练至关重要，全面提升腕力。', 'STRENGTH', 'INTERMEDIATE', 60, 104, 'APPROVED', 4.4, 200);
SET @c = LAST_INSERT_ID();
INSERT INTO course_exercise (course_id, title, video_url, description, sort_order) VALUES
(@c, 'Cable Wrist Curl', '/exercises/Cable_Wrist_Curl/', 'Start out by placing a flat bench in front of a low pulley cable that has a straight bar attachment. Use your arms to grab the cable bar with a narrow to shoulder width supinated grip (palms up) and bring them up so that your forearms are resting against the top of your thighs. Your wrists should be hanging just beyond your knees. Start out by curling your wrist upwards and exhaling. Keep the contraction for a second. Slowly lower your wrists back down to the starting position while inhaling.', 1),
(@c, 'Finger Curls', '/exercises/Finger_Curls/', 'Hold a barbell with both hands and your palms facing up; hands spaced about shoulder width. Place your feet flat on the floor, at a distance that is slightly wider than shoulder width apart. This will be your starting position. Lower the bar as far as possible by extending the fingers. Allowing the bar to roll down the hands, catch the bar with the final joint in the fingers. Now curl bar up as high as possible by closing your hands while exhaling. Hold the contraction at the top.', 2),
(@c, 'Kneeling Forearm Stretch', '/exercises/Kneeling_Forearm_Stretch/', 'Start by kneeling on a mat with your palms flat and your fingers pointing back toward your knees. Slowly lean back keeping your palms flat on the floor until you feel a stretch in your wrists and forearms. Hold for 20-30 seconds.', 3),
(@c, 'Bottoms-Up Clean From The Hang Position', '/exercises/Bottoms-Up_Clean_From_The_Hang_Position/', 'Initiate the exercise by standing upright with a kettlebell in one hand. Swing the kettlebell back forcefully and then reverse the motion forcefully. Crush the kettlebell handle as hard as possible and raise the kettlebell to your shoulder.', 4),
(@c, 'Dumbbell Lying Pronation', '/exercises/Dumbbell_Lying_Pronation/', 'Lie on a flat bench face down with one arm holding a dumbbell and the other hand on top of the bench folded so that you can rest your head on it. Bend the elbows of the arm holding the dumbbell so that it creates a 90-degree angle between the upper arm and the forearm. Now raise the upper arm so that the forearm is perpendicular to the floor and the upper arm is perpendicular to your torso. Tip: The upper arm should be parallel to the floor and also creating a 90-degree angle with your torso. This will be your starting position. As you breathe out, externally rotate your forearm so that the du', 5);
